### ISSUE TITLE
Is this mod still functuonal?

### ISSUE THREAD

**Issue by Kablumbaa** [Zaggy1024/LC_PathfindingLagFix#2]
Is this mod still functuonal? Doesn't seem to work on my end.

**Comment by Zaggy1024** [comment]
As far as I'm aware, nothing about the code that is patched in this mod has changed in Lethal Company v50. What makes you say that it doesn't work, are you getting lag spikes associated with a certain enemy?

**Comment by Kablumbaa** [comment]
@Zaggy1024 Yeah especially with the new tulip snake creature.. When they are present on the map these FS 1 logs spam like crazy, the game starts to stutter and my fps goes down from 70-80 to 50-60. 
![image](https://github.com/Zaggy1024/LC_PathfindingLagFix/assets/167421950/d27475e1-59a5-41cc-8a8f-7acb1c077455)

**Comment by Zaggy1024** [comment]
The tulip snake isn't currently patched by PathfindingLagFix, and the issue here isn't with pathfinding. That "FS 1" prints in the AI interval function that runs every 200ms, and it would normally be accompanied by a print of "FS 2" if it did any synchronous pathfinding.

Printing to the log doesn't normally take long enough to drop the framerate that drastically unless it's done multiple times per frame, but if the drive that your log is written to is particularly slow, perhaps that could contribute.

I'll consider making a patch for this, but it's not high on my priority list at the moment, and I would imagine that Zeekers may put out a patch before long that removes it and fixes a few outstanding bugs.

**Comment by Kablumbaa** [comment]
I see, maybe it is a problem on the creature itself but not on log. Both the game and the modmanager is on my m2 ssd. I will probably change the tulip snake spawnrate to 0 because it feels really cranky to play with them present.

**Comment by Zaggy1024** [comment]
I believe this spam is no longer present in the game, thankfully.
