### ISSUE TITLE
Can this mod be used by the host only?

### ISSUE THREAD

**Issue by The-Haxor** [Zaggy1024/LC_PathfindingLagFix#4]
Hello. I want to know if I'm able, as a public lobby host, to use this mod without risking desyncs or other incompatibility issues with vanilla clients.

**Comment by Zaggy1024** [comment]
I can't guarantee that it won't cause desyncs, since it does change the amount of in-game time that it takes for a path to be chosen, and can sometimes change the chosen path (usually when nothing is accessible due to line-of-sight checks).

From my understanding of the networking of enemies, the clients will run the pathing code as well, and if the chosen path differs from the host, the enemies may jitter or teleport from the client's chosen path to the position that the host determines for the enemy.

It's also possible that the host doesn't send enough synchronization packets to the client for the differing pathing to be corrected consistently, in which case clients may never see enemies at the same position that the host sees them.

I would recommend testing this with someone to see if anything weird happens, and feel free to report back here, but it's not a configuration I want to support myself.

**Comment by broken-usb** [comment]
I played a bit with it and it seems to work altought the Bracken will act weird, the most notable issue is that when there is more than 2 players nearby (one of them being the host) the Bracken seems to get confused in wich path to take, sometimes stopping mid retreating and remaining stopped for about 3 seconds then suddendly going into a complety different direction from the one he was going before (this causes the Bracken to sometimes run into players while in it's retreating state or just stop right in front of a player preventing them to move(since they would die if they touch the Bracken)), this can happen multiple times during it's retreating state.

**Comment by Zaggy1024** [comment]
That can possibly also be caused by moving between two halves of the map when you spot the Bracken near the center, since the retreating Bracken is trying to choose the furthest location from the closest player to it. This can happen in vanilla as well. Given that, it's hard to say whether the issue you experienced is caused by running this mod on the host only.

I also forgot to note, installing the mod on the host will not reduce the lag experienced by clients in the game, as the same logic runs on both the host and the clients. Running the mod only on the client may also experience similar issues to running only on the host.
